package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Assure generated by hbm2java
 */
@Entity
@Table(name = "assure")
public class Assure implements java.io.Serializable {
    
	@Id
	private int cleAssure;
	@ManyToOne
	private CodeExploitation codeExploitation;
	private int numAssure;
	private String nom;
	private String prenom;
	private String statut;
	@OneToOne
	private AvantageAssure avantageAssures ;

	public Assure() {
	}

	public int getCleAssure() {
		return cleAssure;
	}

	public void setCleAssure(int cleAssure) {
		this.cleAssure = cleAssure;
	}

   

	public CodeExploitation getCodeExploitation() {
		return codeExploitation;
	}

	public void setCodeExploitation(CodeExploitation codeExploitation) {
		this.codeExploitation = codeExploitation;
	}

	public int getNumAssure() {
		return numAssure;
	}

	public void setNumAssure(int numAssure) {
		this.numAssure = numAssure;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getStatut() {
		return statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public AvantageAssure getAvantageAssures() {
		return avantageAssures;
	}

	public void setAvantageAssures(AvantageAssure avantageAssures) {
		this.avantageAssures = avantageAssures;
	}

	
}
