package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AvantageAssure generated by hbm2java
 */
@Entity
@Table(name = "avantage_assure")
public class AvantageAssure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private int cleAvantage;
	private float taux;

	public AvantageAssure() {
	}

	public int getCleAvantage() {
		return cleAvantage;
	}

	public void setCleAvantage(int cleAvantage) {
		this.cleAvantage = cleAvantage;
	}

	public float getTaux() {
		return taux;
	}

	public void setTaux(float taux) {
		this.taux = taux;
	}
	
	

}
