package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caissier generated by hbm2java
 */
@Entity
@Table(name = "caissier")
public class Caissier implements java.io.Serializable {

	@Id

	@Column(name = "cle_caissier", unique = true, nullable = false)
	private int cleCaissier;
	private int nom;
	private int prenom;
	@OneToMany
	private Set<Paiement> paiements = new HashSet<Paiement>(0);

	public Caissier() {
	}

	public int getCleCaissier() {
		return cleCaissier;
	}

	public void setCleCaissier(int cleCaissier) {
		this.cleCaissier = cleCaissier;
	}

	public int getNom() {
		return nom;
	}

	public void setNom(int nom) {
		this.nom = nom;
	}

	public int getPrenom() {
		return prenom;
	}

	public void setPrenom(int prenom) {
		this.prenom = prenom;
	}

	public Set<Paiement> getPaiements() {
		return paiements;
	}

	public void setPaiements(Set<Paiement> paiements) {
		this.paiements = paiements;
	}

	

}
