package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Connexion generated by hbm2java
 */
@Entity
@Table(name = "connexion")
public class Connexion implements java.io.Serializable {

	private ConnexionId id;

	public Connexion() {
	}

	public Connexion(ConnexionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "login", column = @Column(name = "login", nullable = false, length = 15)),
			@AttributeOverride(name = "mdp", column = @Column(name = "mdp", nullable = false, length = 15)),
			@AttributeOverride(name = "statut", column = @Column(name = "statut", nullable = false, length = 20)) })
	public ConnexionId getId() {
		return this.id;
	}

	public void setId(ConnexionId id) {
		this.id = id;
	}

}
