package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employeur generated by hbm2java
 */
@Entity
@Table(name = "employeur")
public class Employeur implements java.io.Serializable {

	@Id
	private int cleEmp;
	@ManyToMany
	@JoinTable(name = "employeurs_region", joinColumns = {
			@JoinColumn(name = "cleEmp", referencedColumnName = "cleEmp") }, inverseJoinColumns = {
					@JoinColumn(name = "cleReg", referencedColumnName = "cleReg") })
	private Set<Region> regions = new HashSet<Region>(0);

	private int numEmp;
	private String nom;
	private String prenom;
	@OneToMany
	private Set<CodeExploitation> codeExploitations = new HashSet<CodeExploitation>(0);

	@OneToMany
	private Set<Paiement> paiements = new HashSet<Paiement>(0);
	

	public Employeur() {
	}

	public int getCleEmp() {
		return cleEmp;
	}

	public void setCleEmp(int cleEmp) {
		this.cleEmp = cleEmp;
	}

	

	public Set<Region> getRegions() {
		return regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

	public int getNumEmp() {
		return numEmp;
	}

	public void setNumEmp(int numEmp) {
		this.numEmp = numEmp;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Set<CodeExploitation> getCodeExploitations() {
		return codeExploitations;
	}

	public void setCodeExploitations(Set<CodeExploitation> codeExploitations) {
		this.codeExploitations = codeExploitations;
	}

	public Set<Paiement> getPaiements() {
		return paiements;
	}

	public void setPaiements(Set<Paiement> paiements) {
		this.paiements = paiements;
	}


	

}
