package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name = "paiement")
public class Paiement implements java.io.Serializable {

	@Id
	@Column(name = "cle_paiement", unique = true, nullable = false)
	private int clePaiement;
	@ManyToOne
	private Caissier caissier;
	@ManyToOne
	private Employeur employeur;
	@OneToOne
	private Penalite penalite;
	private int montant;
	private Date date;
	private int trimestre;
	private int annee;


	public Paiement() {
	}


	public int getClePaiement() {
		return clePaiement;
	}


	public void setClePaiement(int clePaiement) {
		this.clePaiement = clePaiement;
	}


	public Caissier getCaissier() {
		return caissier;
	}


	public void setCaissier(Caissier caissier) {
		this.caissier = caissier;
	}


	public Employeur getEmployeur() {
		return employeur;
	}


	public void setEmployeur(Employeur employeur) {
		this.employeur = employeur;
	}


	public Penalite getPenalite() {
		return penalite;
	}


	public void setPenalite(Penalite penalite) {
		this.penalite = penalite;
	}


	public int getMontant() {
		return montant;
	}


	public void setMontant(int montant) {
		this.montant = montant;
	}


	public Date getDate() {
		return date;
	}


	public void setDate(Date date) {
		this.date = date;
	}


	public int getTrimestre() {
		return trimestre;
	}


	public void setTrimestre(int trimestre) {
		this.trimestre = trimestre;
	}


	public int getAnnee() {
		return annee;
	}


	public void setAnnee(int annee) {
		this.annee = annee;
	}

	
}
