package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Penalite generated by hbm2java
 */
@Entity
@Table(name = "penalite")
public class Penalite implements java.io.Serializable {

	@Id
	private int clePenalite;
	private int nbJours;
	private float taux;
	private float montant;
	private int trimestre;
	private int annee;
	@OneToMany
	private Set<ResponsablePenalite> responsablePenalites = new HashSet<ResponsablePenalite>(0);

	public Penalite() {
	}

	public int getClePenalite() {
		return clePenalite;
	}

	public void setClePenalite(int clePenalite) {
		this.clePenalite = clePenalite;
	}

	public int getNbJours() {
		return nbJours;
	}

	public void setNbJours(int nbJours) {
		this.nbJours = nbJours;
	}

	public float getTaux() {
		return taux;
	}

	public void setTaux(float taux) {
		this.taux = taux;
	}

	public float getMontant() {
		return montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

	public int getTrimestre() {
		return trimestre;
	}

	public void setTrimestre(int trimestre) {
		this.trimestre = trimestre;
	}

	public int getAnnee() {
		return annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	

	public Set<ResponsablePenalite> getResponsablePenalites() {
		return responsablePenalites;
	}

	public void setResponsablePenalites(Set<ResponsablePenalite> responsablePenalites) {
		this.responsablePenalites = responsablePenalites;
	}

	
}
