package com.cnss.pfe.persistance.model;
// Generated 21 avr. 2019 12:25:46 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResponsablePenalite generated by hbm2java
 */
@Entity
@Table(name = "responsable_penalite")
public class ResponsablePenalite implements java.io.Serializable {

	@Id
	private int cleResp;
	private Penalite penalite;
	private String nom;
	private String prenom;
	@ManyToOne
	private Penalite penalites;

	public ResponsablePenalite() {
	}

	public int getCleResp() {
		return cleResp;
	}

	public void setCleResp(int cleResp) {
		this.cleResp = cleResp;
	}

	public Penalite getPenalite() {
		return penalite;
	}

	public void setPenalite(Penalite penalite) {
		this.penalite = penalite;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Penalite getPenalites() {
		return penalites;
	}

	public void setPenalites(Penalite penalites) {
		this.penalites = penalites;
	}
	

}
